### ISSUE TITLE
Cache JSON schema

### ISSUE THREAD

**Issue by Hades32** [supabase/pg_jsonschema#13]
Just an improvement idea:

As I assume this is mostly going to be used in `CHECK` constraints, the number of schemas in use will be very small. It would probably speed up validation a bit if you compiled the schemas and added a (LRU?) cache for them

**Comment by olirice** [comment]
the tradeoff with cacheing is that it requires registering `pg_jsonschema` with `shared_preload_libraries`. That then forces any future upgrade to require a PostgreSQL server reboot

if we get reports of a major use-case where the current setup is a performance bottleneck we can look at further optimizations (open to suggestions!) but for the time being we'd prefer to keep the operational simplicity

**Comment by jefbarn** [comment]
@olirice 
You can set up a cache per thread. See my branch:
https://github.com/jefbarn/pgx_json_schema/tree/cached

**Comment by jefbarn** [comment]
@olirice 
FYI, I haven't done any testing on that branch, as I'm not using this library in my day job anymore. That's why it's on an unreleased branch.
As for using a hash for the cache key, I was worried that the hashing time would be significant if a giant schema was used. Another alternative I was considering is just to use the id or $id field (depending on schema version). You could fall back to hash if that wasn't available.
